apiVersion: v1
kind: Service
metadata:
  name: postgres-tailscale
  namespace: {{ .Values.namespace }}
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: {{ .Values.tailscale.hostname }}
    tailscale.com/tags: {{ .Values.tailscale.tag }}
spec:
  type: ClusterIP
  selector:
    cnpg.io/cluster: postgres-cluster
    cnpg.io/instanceRole: primary
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
