zitadel:
  masterkeySecretName: zitadel-credentials
  configmapConfig:
    ExternalSecure: true
    ExternalPort: 443
    TLS:
      Enabled: false
    Database:
      Postgres:
        Host: postgres-cluster-rw.databases.svc.cluster.local
        Port: 5432
        Database: zitadel
        MaxOpenConns: 10
        MaxIdleConns: 5
        MaxConnLifetime: 30m
        MaxConnIdleTime: 5m
        User:
          Username: zitadel
          SSL:
            Mode: disable
        Admin:
          Username: postgres
          SSL:
            Mode: disable
    FirstInstance:
      Org:
        Human:
          UserName: admin
          FirstName: Admin
          LastName: User
          Email:
            Verified: true
          PasswordChangeRequired: true
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
envVarsSecret: zitadel-credentials
postgresql:
  enabled: false
