apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.credentialName }}
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: {{ .Values.credentialName }}
  dataFrom:
    - extract:
        key: secret/zitadel
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
