{{- $host := include "zitadel-resources.host" . -}}
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: zitadel
  namespace: {{ .Values.namespace }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ $host }}
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: zitadel-tls
      hosts:
        - {{ $host }}
    - port:
        number: 80
        name: http
        protocol: HTTP
      tls:
        httpsRedirect: true
      hosts:
        - {{ $host }}
