apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: vaultwarden
  namespace: {{ .Values.namespace }}
spec:
  hosts:
    - {{ include "vaultwarden-resources.host" . }}
  gateways:
    - vaultwarden
  http:
    - route:
        - destination:
            host: vaultwarden
            port:
              number: 80
