apiVersion: v1
kind: Service
metadata:
  name: longhorn-tailscale
  namespace: {{ .Values.namespace }}
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: {{ .Values.tailscale.hostname }}
    tailscale.com/tags: {{ .Values.tailscale.tag }}
spec:
  type: ClusterIP
  selector:
    app: longhorn-ui
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
