apiVersion: v1
kind: Service
metadata:
  name: vault-tailscale
  namespace: {{ .Values.namespace }}
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: {{ .Values.tailscale.hostname }}
    tailscale.com/tags: {{ .Values.tailscale.tag }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: vault
    component: server
  ports:
    - name: http
      port: 80
      targetPort: 8200
      protocol: TCP
